name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Auto-label PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Label based on changed files
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
